server +0.1

diff --git a/server/sbin/database b/server/sbin/database
--- a/server/sbin/database
+++ b/server/sbin/database
@@ -6,7 +6,7 @@ BASENAME=`basename ${FILE}`
 
 HELP="
 Description: Create database and user in mariadb.
-Usage: ${BASENAME} <create|delete> <database> <user> <password>
+Usage: ${BASENAME} <create|delete> <database>
 "
 if test "${1}" = "-h" -o "${1}" = "--help"
 then
@@ -31,14 +31,13 @@ create_database ()
 	notice "Create database and user in mariadb"
 	
 	DATABASE="${1}"
-	USER="${2}"
-	PASSWORD="${3}"
-	### /usr/bin/apg -n 1 -m 8 -x 8 -M NCL	
+	USER="${1}"
+	PASSWORD=`/usr/bin/apg -n 1 -m 8 -x 8 -M NCL`
 
 	QUERY="
-CREATE DATABASE \`${DATABASE}\`;
-CREATE USER \`${USER}\`@\`localhost\` IDENTIFIED BY '${PASSWORD}';
-GRANT ALL ON \`${DATABASE}\`.* TO \`${USER}\`@\`localhost\`;
+CREATE DATABASE ${DATABASE};
+CREATE USER '${USER}'@'localhost' IDENTIFIED BY '${PASSWORD}';
+GRANT ALL ON ${DATABASE}.* TO '${USER}'@'localhost';
 "
 	/usr/bin/echo "${QUERY}" | /usr/bin/mysql -v
 	if test $? -ne 0
@@ -46,6 +45,15 @@ GRANT ALL ON \`${DATABASE}\`.* TO \`${USER}\`@\`localhost\`;
 		error "Can't create database or user"
 		return 255
 	fi
+	
+	echo "
+Database created
+
+name: ${DATABASE}
+user: ${USER}
+password: ${PASSWORD}
+
+"
 	return 0
 }
 
@@ -54,22 +62,30 @@ delete_database ()
 	notice "Delete database and user from mariadb"
 	
 	DATABASE="${1}"
-	USER="${2}"
+	USER="${1}"
 	STATUS=0
 	
-	QUERY="DROP DATABASE \`${DATABASE}\`;"
+	QUERY="REVOKE ALL ON ${DATABASE}.* FROM '${USER}'@'localhost';"
 	/usr/bin/echo "${QUERY}" | /usr/bin/mysql -v
 	if test $? -ne 0
 	then
-		error "Can't delete database"
+		error "Can't revoke on database"
 		STATUS=255
 	fi
 	
-	QUERY="DROP USER \`${USER}\`@\`localhost\`;"
+	QUERY="DROP USER '${USER}'@'localhost';"
 	/usr/bin/echo "${QUERY}" | /usr/bin/mysql -v
 	if test $? -ne 0
 	then
-		error "Can't delete user"
+		error "Can't drop user"
+		STATUS=255
+	fi
+	
+	QUERY="DROP DATABASE ${DATABASE};"
+	/usr/bin/echo "${QUERY}" | /usr/bin/mysql -v
+	if test $? -ne 0
+	then
+		error "Can't drop database"
 		STATUS=255
 	fi
 	
@@ -89,18 +105,8 @@ case ${1} in
 			error "Database name is not passed"
 			exit 255
 		fi
-		if test -z "${3}"
-		then
-			error "User name is not passed"
-			exit 255
-		fi
-		if test -z "${4}"
-		then
-			error "Password is not passed"
-			exit 255
-		fi
 		
-		create_database "${2}" "${3}" "${4}"
+		create_database "${2}"
 		
 		;;
 	"delete")
@@ -109,13 +115,8 @@ case ${1} in
 			error "Database name is not passed"
 			exit 255
 		fi
-		if test -z "${3}"
-		then
-			error "User name is not passed"
-			exit 255
-		fi
 		
-		delete_database "${2}" "${3}"
+		delete_database "${2}"
 		
 		;;
 	*)
diff --git a/server/sbin/user b/server/sbin/user
--- a/server/sbin/user
+++ b/server/sbin/user
@@ -5,7 +5,7 @@ DIR=`/usr/bin/dirname ${FILE}`
 BASENAME=`basename ${FILE}`
 
 HELP="
-Description: Create folders for 'ilamp' site.
+Description: Add user to the system with specific options for 'ilamp'.
 Usage: ${BASENAME} <create|delete> <user_name>
 "
 if test "${1}" = "-h" -o "${1}" = "--help"
@@ -26,39 +26,39 @@ notice ()
 	return 0
 }
 
-create_folders ()
+create_user ()
 {
-	notice "Create folders for site"
-	USER="${1}"
-	for COMMAND in \
-"/usr/bin/mkdir -m 750 /srv/${USER}" \
-"/usr/bin/chown root:${USER} /srv/${USER}" \
-"/usr/bin/mkdir -m 750 /srv/${USER}/log" \
-"/usr/bin/chown root:${USER} /srv/${USER}/log" \
-"/usr/bin/mkdir -m 770 /srv/${USER}/www" \
-"/usr/bin/chown root:${USER} /srv/${USER}/www" \
-"/usr/bin/mkdir -m 770 /srv/${USER}/mail" \
-"/usr/bin/chown root:${USER} /srv/${USER}/mail"
-	do
-		echo "${COMMAND}"
-		$COMMAND
-		if test $? -ne 0
-		then
-			error "exec ${COMMAND} error"
-			return 255
-		fi
-	done
+	notice "Create user on system"
+	LOGIN="${1}"
+	COMMAND="/usr/sbin/useradd \
+		--comment '' \
+		--home-dir /srv/${LOGIN}/home \
+		-K USERGROUPS_ENAB=yes -K UID_MIN=33000 -K GID_MIN=33000 \
+		--no-create-home \
+		--shell /usr/sbin/nologin \
+		--user-group \
+		${LOGIN}
+	"
+	echo $COMMAND
+	$COMMAND
+	if test $? -ne 0
+	then
+		error "Can't create user on system"
+		return 255
+	fi
 	return 0
 }
 
-delete_folders ()
+delete_user ()
 {
-	notice "Delete site folders"
-	USER="${1}"
-	/usr/bin/rm -r -v /srv/${USER}
+	notice "Delete user from system"
+	LOGIN="${1}"
+	COMMAND="/usr/sbin/userdel ${LOGIN}"
+	echo $COMMAND
+	$COMMAND
 	if test $? -ne 0
 	then
-		echo "Can't delete folders"
+		error "Can't delete user from system"
 		return 255
 	fi
 	return 0
@@ -78,7 +78,7 @@ case ${1} in
 			exit 255
 		fi
 		
-		create_folders "${2}"
+		create_user "${2}"
 		
 		;;
 	"delete")
@@ -88,7 +88,7 @@ case ${1} in
 			exit 255
 		fi
 		
-		delete_folders "${2}"
+		delete_user "${2}"
 		
 		;;
 	*)
